version: '3'

tasks:
  build:
    desc: Build both backend and frontend
    aliases: [b]
    cmds:
      - task: build:backend
      - task: build:frontend

  build:backend:
    desc: Build the backend .NET project
    aliases: [bb]
    dir: backend/TurbineTrack
    cmds:
      - dotnet build

  build:frontend:
    desc: Build the frontend Vite app
    aliases: [bf]
    dir: frontend
    cmds:
      - npm run build

  start:backend:
    desc: Run the backend with dotnet watch
    aliases: [rb]
    dir: backend/TurbineTrack
    cmds:
      - dotnet watch run

  start:frontend:
    desc: Run the frontend dev server
    aliases: [rf]
    dir: frontend
    cmds:
      - npm run dev

  docker:build:
    desc: Build Docker containers
    aliases: [db]
    cmds:
      - docker compose build

  docker:up:
    desc: Start Docker containers
    aliases: [dup]
    cmds:
      - docker compose up -d

  docker:down:
    desc: Stop and remove Docker containers
    aliases: [ddn]
    cmds:
      - docker compose down

  docker:logs:
    desc: View Docker logs
    aliases: [dlog]
    cmds:
      - docker compose logs -f

  db:update:
    desc: Run EF Core migration
    aliases: [ef]
    dir: backend/TurbineTrack
    cmds:
      - dotnet ef database update

  test:
    desc: Run backend tests
    aliases: [t]
    dir: backend/TurbineTrack.Tests
    cmds:
      - dotnet test
