version: '3'

vars:
  FRONTEND_DIR: ./frontend
  BACKEND_DIR: ./backend/TurbineTrack
  TESTS_DIR: ./backend/TurbineTrack.Tests

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # ────── BUILD TASKS ──────
  build:
    desc: Build both backend and frontend
    aliases: [b]
    cmds:
      - task: build:backend
      - task: build:frontend

  build:backend:
    desc: Build the backend .NET project
    aliases: [bb]
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - dotnet build

  build:frontend:
    desc: Build the frontend Vite app
    aliases: [bf]
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - npm run build

  # ────── DEV TASKS ──────
  start:backend:
    desc: Run the backend with dotnet watch
    aliases: [rb]
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - dotnet watch run

  start:frontend:
    desc: Run the frontend dev server
    aliases: [rf]
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - npm run dev

  # ────── DOCKER TASKS ──────
  docker:build:
    desc: Build Docker containers
    aliases: [db]
    cmds:
      - docker compose build

  docker:up:
    desc: Start Docker containers
    aliases: [dup]
    cmds:
      - docker compose up -d

  docker:down:
    desc: Stop and remove Docker containers
    aliases: [ddn]
    cmds:
      - docker compose down

  docker:logs:
    desc: View Docker logs
    aliases: [dlog]
    cmds:
      - docker compose logs -f

  docker:run:backend:
    desc: Run backend Docker container (development mode)
    aliases: [drb]
    cmds:
      - docker run -e ASPNETCORE_ENVIRONMENT=Development -p 8080:8080 turbine-api

  # ────── DATABASE TASKS ──────
  db:update:local:
    desc: Apply EF Core migrations locally
    aliases: [efl]
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - dotnet ef database update

  db:update:docker:
    desc: Apply EF Core migrations in Docker
    aliases: [efd]
    cmds:
      - docker exec turbinetrack_api_dev dotnet ef database update

  # ────── TEST TASKS ──────
  test:
    desc: Run backend tests
    aliases: [t]
    dir: "{{.TESTS_DIR}}"
    cmds:
      - dotnet test
