version: '3'

tasks:
  install:
    desc: Install dependencies for both frontend and backend
    cmds:
      - task: install:frontend
      - task: install:backend

  build:
    desc: Build both frontend and backend
    cmds:
      - task: build:frontend
      - task: build:backend

  test:
    desc: Run tests for both frontend and backend
    cmds:
      - task: test:frontend
      - task: test:backend

  install:frontend:
    desc: Install frontend dependencies
    dir: frontend
    cmds:
      - npm install

  install:backend:
    desc: Install backend dependencies
    dir: backend
    cmds:
      - dotnet restore

  build:frontend:
    desc: Build frontend
    dir: frontend
    cmds:
      - npm run build

  build:backend:
    desc: Build backend
    dir: backend
    cmds:
      - dotnet build

  start:frontend:
    desc: Start frontend development server
    dir: frontend
    cmds:
      - npm start

  start:backend:
    desc: Start backend server
    dir: backend
    cmds:
      - dotnet run

  test:backend:
    desc: Run backend tests
    dir: backend
    cmds:
      - dotnet test

