FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /app
COPY . .

# Install EF CLI
RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"

RUN dotnet restore
RUN dotnet build

# Set the entry point with explicit URLs
ENTRYPOINT ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:8080"]
